Feature/layout footer
obsidian-software-service/korova-website pull request #6
Opened 2021-02-02 23:24 UTC by DIOLINK

![image](https://user-images.githubusercontent.com/54718297/106675770-7d7f6c00-6594-11eb-8255-f1c66a118187.png)

2021-02-03 00:37 UTC, adrianponce89 requested changes

2021-02-03 00:37 UTC, adrianponce89 commented on src/components/Footer.jsx
> +            OCTOSOFT
Ponele Korova al menos xD, copy pastero jajajja

2021-02-03 00:37 UTC, adrianponce89 commented on src/components/Footer.jsx
> +              to="https://octosoftprofessionals.com/"
Cambia todos los https://octosoftprofessionals.com/ por /

2021-02-03 22:40 UTC, adrianponce89 commented
@DIOLINK por favor entra a https://deploy-preview-6--korova-digital.netlify.app/ y vas a notar que esta mal alineado, eso es por la posicion donde estás incluyendo el footer

2021-02-03 22:43 UTC, adrianponce89 requested changes

2021-02-03 22:43 UTC, adrianponce89 commented on src/components/layout.js
>        </ThemeProvider>
Cambialo por:
```
      <ThemeProvider theme={theme}>
        <NavBar />
        <main>
          {children}
          <Footer />
        </main>
      </ThemeProvider>
```

Para evitar que se desalinee como en https://deploy-preview-6--korova-digital.netlify.app/

2021-02-04 00:09 UTC, DIOLINK commented
![image](https://user-images.githubusercontent.com/54718297/106825676-21841880-6664-11eb-82a5-cf37eb0ff53a.png)

2021-02-04 15:58 UTC, DIOLINK commented
![Peek 04-02-2021 12-57](https://user-images.githubusercontent.com/54718297/106919207-afa1e280-66e8-11eb-8fa8-1289c0a4fe37.gif)

2021-02-07 16:23 UTC, adrianponce89 approved these changes

2021-02-07 16:23 UTC, adrianponce89 commented on gatsby-config.js
> +          injectFirst: true,
Maravilloso!!

2021-02-07 17:19 UTC, merged